export const season9ChampionList = [
  { name: "Aatrox", cost: 5, myCount: 0, enemyCount: 0 },
  { name: "Ahri", cost: 5, myCount: 0, enemyCount: 0 },
  { name: "Akshan", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Aphelios", cost: 4, myCount: 0, enemyCount: 0 },
  { name: "Ashe", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "Azir", cost: 4, myCount: 0, enemyCount: 0 },
  { name: "BelVeth", cost: 5, myCount: 0, enemyCount: 0 },
  { name: "Cassiopeia", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "ChoGath", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "Darius", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Ekko", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Galio", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "Garen", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Gwen", cost: 4, myCount: 0, enemyCount: 0 },
  { name: "Heimerdinger", cost: 5, myCount: 0, enemyCount: 0 },
  // { name: "HeimerdingerTurret", cost: 5, myCount: 0, enemyCount: 0 },
  { name: "Irelia", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "JarvanIV", cost: 4, myCount: 0, enemyCount: 0 },
  { name: "Jayce", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Jhin", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "Jinx", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "KaiSa", cost: 4, myCount: 0, enemyCount: 0 },
  { name: "Kalista", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Karma", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Kassadin", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "Katarina", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Kayle", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "Kled", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "KSante", cost: 5, myCount: 0, enemyCount: 0 },
  { name: "Lissandra", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Lux", cost: 4, myCount: 0, enemyCount: 0 },
  { name: "Malzahar", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "Maokai", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "Nasus", cost: 4, myCount: 0, enemyCount: 0 },
  { name: "Orianna", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "Poppy", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "Renekton", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "RekSai", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Ryze", cost: 5, myCount: 0, enemyCount: 0 },
  { name: "Samira", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "Sejuani", cost: 4, myCount: 0, enemyCount: 0 },
  { name: "Senna", cost: 5, myCount: 0, enemyCount: 0 },
  { name: "Sett", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "Shen", cost: 4, myCount: 0, enemyCount: 0 },
  { name: "Sion", cost: 5, myCount: 0, enemyCount: 0 },
  { name: "Sona", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Soraka", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "Swain", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "Taliyah", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "Taric", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Teemo", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "Tristana", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "Urgot", cost: 4, myCount: 0, enemyCount: 0 },
  { name: "VelKoz", cost: 3, myCount: 0, enemyCount: 0 },
  { name: "Viego", cost: 1, myCount: 0, enemyCount: 0 },
  { name: "Vi", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "Warwick", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "Yasuo", cost: 4, myCount: 0, enemyCount: 0 },
  { name: "Zed", cost: 2, myCount: 0, enemyCount: 0 },
  { name: "Zeri", cost: 4, myCount: 0, enemyCount: 0 },
];

export interface TFTLegendMap {
  [key: number]: string;
}

export const TFTLegendMap: TFTLegendMap = {
  27: "AurelionSol",
  28: "Bard",
  23: "Caitlyn",
  19: "Draven",
  18: "Ezreal",
  26: "LeeSin",
  25: "MasterYi",
  22: "Ornn",
  24: "Pengu",
  16: "TahmKench",
  20: "TwistedFate",
  21: "Urf",
  15: "Veigar",
  17: "Vladimir",
};

export const extraUnitList = [
  "TFT9_NoxianFlag",
  "TFT_TrainingDummy",
  "TFT9_THex",
  "TFT9_VoidEggHerald",
  "TFT9_VoidEggRemora",
  "TFT9_VoidEggBaron",
  "TFT9_HeimerdingerTurret",
];
